#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# bvs find url cmd
# php bin/console debug:router

vehicle_list:
  path: /api/vehicles
  controller: App\Controller\VehicleController:indexAction
  methods: [GET]
vehicle_create:
  path: /api/vehicles
  controller: App\Controller\VehicleController:createAction
  methods: [POST]
